kind: Secret
apiVersion: v1
metadata:
  name: gitea
  namespace: workshop-int
  annotations:
    tekton.dev/git-0: "https://repository-git.apps.{YOUR_DOMAIN_NAME}/gitea/openshift-gitops-getting-started.git"
data:
  password: Z2l0ZWE=
  username: Z2l0ZWE=
type: kubernetes.io/basic-auth
